services:
  - type: web
    name: tiffin-service-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: tiffin-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: tiffin-service-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
