services:
  - type: web
    name: tiffin-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors 'none'"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: tiffin-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false